# Project: P3Lab4_JorgeZuniga
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Inventario.o Producto.o
LINKOBJ  = main.o Inventario.o Producto.o
LIBS     = -L"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/lib" -L"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/include" -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/include" -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = P3Lab4_JorgeZuniga.exe
CXXFLAGS = $(CXXINCS) -std=c++11 -g3
CFLAGS   = $(INCS) -std=c++11 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Inventario.o: Inventario.cpp
	$(CPP) -c Inventario.cpp -o Inventario.o $(CXXFLAGS)

Producto.o: Producto.cpp
	$(CPP) -c Producto.cpp -o Producto.o $(CXXFLAGS)
